### ISSUE TITLE
Persist v-network-graph node meta data in database

### ISSUE THREAD

**Issue by capital-G** [Gencaster/gencaster#54]
* [x] List of node metadata that needs to be persistent on the database (e.g. position, color?)
* [x] We need to improve the 1-way binding of graphql-data to v-network-graph data, I think this doc could help? https://formidable.com/open-source/urql/docs/graphcache/local-resolvers/
* [x] Bonus point / optional : 2 way binding with automatic mutations if e.g. position of node is changed
