### ISSUE TITLE
Add Meta editing to the Editor

### ISSUE THREAD

**Issue by vin-ni** [Gencaster/gencaster#564]
### Frontend
- [x] Name
- [x] Display Name
- [x] slug name
- [x] Stream assignment policy:
- [x] Start Text (Markdown)
- [x] About Text (Markdown)
- [x] End Text (Markdown)

### Backend
- [x] Update Graphql to offer Streamassignment options
- [x] Add StreamingAssignment in Graphql request
- [x] Subscription for Meta Mutation
- [x] Validation? (maybe skipable for now, since we don't change the slug)
- [x] Submit to DB 

This should only be updated on submit and not subscribed. What do you think @capital-G ?

**Comment by capital-G** [comment]
Sounds like a good idea - maybe like a [`ElCard`](https://element-plus.org/en-US/component/card.html) which contains a [`ElForm`](https://element-plus.org/en-US/component/form.html)?

Currently the backend mutation for this is not implemented yet.

**Comment by vin-ni** [comment]
I rather thought about a full page displaying all potential updates. I'll prepare a proposition.
