### ISSUE TITLE
Meta: Feedback from Gencaster workshop

### ISSUE THREAD

**Issue by capital-G** [Gencaster/gencaster#589]
## Bugs

* [ ] Switching between graphs in the editor will not update the meta
* [ ] Going back on the frontend does not terminate the stream
* [ ] #588 
* [ ] #586 
* [ ] Custom markdown does not work, e.g. {eval}\`2+2\`
* [ ] https://github.com/Gencaster/gencaster/issues/559
* [ ] https://github.com/Gencaster/gencaster/commit/277c9117bf85da7ab93b4431903923179000555a removal of docker host mode leads to non-connections in more restrictive networks, needs to be reverted

And there are lots of sentry issues which I need to dig through

## New Features

* [ ] Select Restart policy in case of a Graph Dead End
* [ ] Add more documentation (e.g. GPS is missing)
* [ ] Send Stream Variables to sclang as well
* [ ] #587 
* [ ] Can Stream Variables be automatically casted within python (e.g. `try: eval(var) else: var`?)
* [ ] Display output nodes in node editor so it is easier to track what the next node could be
* [ ] When node editor is open and creating a new node it is created half off screen (also, maybe create a new one via doubleclick on the canvas?)
* [ ] If deleting a node while the node editor is still open it will result in a dangling node editor - it should close in this case
* [ ] Increase max number of iterations https://github.com/Gencaster/gencaster/blob/519d98dab44d58b2c81e2fa6d63a60509b8d08b1/caster-back/gencaster/schema.py#L630
* [ ] Save/Export graph
* [ ] Add cause of exception on node door execution https://github.com/Gencaster/gencaster/blob/519d98dab44d58b2c81e2fa6d63a60509b8d08b1/caster-back/story_graph/engine.py#L395
* [ ] Add more python libraries to script cell execution runtime: 
  * [ ] requests
  * [ ] random
  * [ ] list
